name: Destroy Terraform

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.REGION_FOR_REMOTE_STATE }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init -backend=true -backend-config="bucket=${{ secrets.BUCKET_FOR_REMOTE_STATE }}" -backend-config="key=${{ secrets.KEY_FOR_REMOTE_STATE }}" -backend-config="region=${{ secrets.REGION_FOR_REMOTE_STATE }}" -backend-config="dynamodb_table=${{ secrets.DYNAMO_TABLE_FOR_REMOTE_STATE }}"
        working-directory: ./terraform

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./terraform
